apiVersion: apps/v1
kind: Deployment
metadata:
  name: goWebServer
  labels:
    app: go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: andrewpark93/ciquickstart:5
        ports:
        - containerPort: 80
